services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
      build:
        context: ./frontend
      container_name: frontend
      ports:
        - "8080:8080"
      volumes:
        - ./frontend:/usr/share/nginx/html

  db:
    image: postgres:14
    container_name: db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
